from pathlib import Path
from seo_metadata import metadata
from PIL import Image,ImageOps
import json,html,re,unicodedata,datetime,shutil,subprocess
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'new-design';AS=OUT/'assets';AS.mkdir(exist_ok=True)
def esc(s):return html.escape(str(s),quote=True)
def slug(s):return re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()).strip('-')
def derivative(src,dst,size):
 if dst.exists():return
 im=ImageOps.exif_transpose(Image.open(src)).convert('RGB');im.thumbnail(size);im.save(dst,'WEBP',quality=88)
art=[]
for p in sorted(Path('/Users/manuariza/Downloads/Antonio Art').glob('*.jpg')):
 title=p.stem.capitalize();s=slug(title);im=ImageOps.exif_transpose(Image.open(p));w,h=im.size
 for width in [700,1800,2600]:derivative(p,AS/f'{s}-{width}.webp',(width,width))
 edge=int(min(w,h)*.42);cx=int(w*.52);cy=int(h*.48);detail=im.crop((cx-edge//2,cy-edge//2,cx+edge//2,cy+edge//2));detail.thumbnail((1200,1200));detail.save(AS/f'{s}-detail.webp',quality=91)
 art.append(dict(title=title,slug=s,width=w,height=h))
for n in [2,3,4]:derivative(ROOT/f'img/bg-img/{n}.jpg',AS/f'studio-{n}.webp',(1800,1800))
posts=list({p['code']:p for p in json.load(open(ROOT/'reports/content-archive/instagram.json'))}.values())
for p in posts:
 for m in p.get('media',[]):
  if m.get('file') and m['type']=='video':
   poster=AS/'restoration'/(m['file']+'.poster.jpg')
   if not poster.exists():subprocess.run(['/opt/homebrew/bin/ffmpeg','-loglevel','error','-ss','0.1','-i',str(AS/'restoration'/m['file']),'-frames:v','1','-vf','scale=900:-2','-y',str(poster)],check=True)

by={p['code']:p for p in posts}
# Editorial summaries are limited to interventions explicitly described by the studio.
case_specs=[
('virgen-de-tomalos','Virgen de Tómalos','Pintura · 1756',['CpUxKd9j7q6'],'Un lienzo con siglos de historia','La suciedad superficial, las deformaciones del lienzo y numerosas roturas convivían con antiguas reparaciones en el reverso. La documentación muestra el estado de la obra, sus detalles y su presentación tras la intervención.','Óleo sobre lienzo · 200 × 140 cm','La limpieza de depósitos biológicos se realizó mecánicamente. Las deformaciones se trataron con presión y calor. El estudio advierte que algunas marcas de corrosión en la pintura son irreversibles.'),
('retrato-de-hombre','Retrato de hombre','Fotografía coloreada · c. 1880',['CiHhxW7j5Tt'],'La fragilidad de una imagen','Una fotografía sobre papel adherida a lienzo y coloreada al óleo. El delicado soporte y las pérdidas de pintura requerían estabilizar la obra antes de su presentación.','Anónimo español · 80 × 60 cm','Consolidación de la pintura sobre el papel fotográfico, limpieza de suciedad superficial y reintegración cromática de las pérdidas.'),
('arcangel-san-rafael','Arcángel San Rafael','Escultura · Siglo XVIII',['Cb8IjyHD99i'],'Conservar la policromía','Una talla de arte popular con pérdidas de policromía y zonas sin adherencia al soporte. La intervención distingue las carnaduras de los ropajes y las alas.','Anónimo español · Madera policromada y dorada · 80 cm','Consolidación y limpieza superficial. Las carnaduras se reintegraron con estuco y color; en los ropajes y alas se aplicó una tinta plana neutra, sin estucar las faltas.'),
('retrato-de-senora','Retrato de señora','Pintura · 1906',['Cbuvs9dq4tP'],'Recuperar la lectura del retrato','Un retrato de Gonzalo Bilbao Martínez. El barniz envejecido y la suciedad alteraban la percepción de los colores, mientras que pintura y soporte conservaban su estabilidad.','Gonzalo Bilbao · Óleo sobre lienzo · 100 × 80 cm','Eliminación del barniz viejo y amarillento y de la suciedad de polución. La comparación original se conserva íntegra.'),
('el-cid','El Cid parte al destierro','Pintura · 1877',['CY015pbjnBi','CbZkskVjtue'],'La estructura de una gran pintura','Julio Cebrián Mezquita representa la despedida del Cid en San Pedro de Cardeña. El lienzo llegó con graves daños en los bordes y pérdida de sujeción al bastidor.','Julio Cebrián Mezquita · Óleo sobre lienzo · 190 × 225 cm','La documentación describe la colocación de bordes de refuerzo y el tratamiento previsto para roturas, pérdidas y barnices oxidados. Estas imágenes muestran un proceso en curso; no acreditan un resultado final.'),
('san-juan-evangelista','Guirnalda con San Juan Evangelista','Pintura · Siglo XVII',['CbFjWUWKX_S'],'El color entre las flores','Una composición de guirnalda floral alrededor de la efigie del santo. Las restauraciones antiguas y los barnices oxidados alteraban su lectura.','Anónimo español · Óleo sobre lienzo · 80 × 60 cm','Retirada de barnices oxidados y reintegración cromática en las zonas donde se había perdido pintura original.'),
('santiago-clavijo','Santiago en la batalla de Clavijo','Pintura · Primera mitad del siglo XVIII',['CUIHAQkjtJg'],'Una pintura, varias capas de historia','Una pintura anónima española cuyo proceso de conservación se documenta mediante una comparación de estados.','Anónimo español · Óleo sobre lienzo · 100 × 80 cm','Sentado de los estratos pictóricos y eliminación de barnices antiguos y suciedad superficial.'),
('retrato-de-nino','Retrato de niño','Pintura · Mediados del siglo XIX',['CTfZqL_DOvh'],'Devolver estabilidad a la pintura','Los cambios de humedad y temperatura, junto con la deficiente fijación al bastidor, habían provocado el desprendimiento de las capas pictóricas.','Anónimo español · Siglo XIX','Consolidación de los estratos pictóricos, recuperación de su adherencia y aplanado del craquelado. Tras ajustar la tensión de la tela, se inició la limpieza del barniz oxidado.'),
('la-piedad','La Piedad','Escultura · Siglos XVII–XVIII',['CS_doW0j8g-'],'Materia, volumen y policromía','Un conjunto en madera de nogal con fendas, desprendimientos, repintes y pérdidas de volumen. Cristo es una talla completa; la Virgen es una imagen de vestir.','Madera de nogal policromada · Siglos XVII–XVIII','Consolidación de madera y policromía, retirada selectiva de repintes, limpieza, reconstrucción de dedos perdidos, estucado, reintegración cromática y barnizado protector. Se conservó el repinte azul del paño de pureza.'),
('pasmado-del-barniz','El pasmado del barniz','Proceso · Vídeo',['CQL9b-wK3bQ'],'Cuando el barniz oculta la pintura','Los halos blanquecinos del barniz pueden velar la imagen. Este vídeo documenta la eliminación de un barniz pasmado en una obra expuesta a un ambiente muy húmedo.','Vídeo de proceso · Reproducción original a 32×','La publicación explica la relación entre humedad y pasmado. La secuencia está acelerada: no representa la duración real del tratamiento.'),
('vida-en-el-estudio','Vida en el estudio','Cuaderno · Enero de 2022',['CYbZ9K4DM0h'],'Un lugar para mirar despacio','Una vista del taller compartida por Antonio al comienzo de 2022, entre obras y nuevos proyectos.','Archivo del estudio','Esta fotografía documenta el espacio de trabajo en la fecha de la publicación.')]
cases=[]
case_specs += [
('calvario-anchieta','Calvario de Juan de Anchieta','Escultura · Siglo XVI',['CLZYraTD__V','CGuPNmkDY5m'],'Una mirada al Renacimiento','Tres tallas de madera dorada y policromada: Cristo, la Virgen y San Juan Evangelista. Las publicaciones del estudio atribuyen el conjunto a Juan de Anchieta.','Juan de Anchieta · Madera de nogal dorada y policromada','En la Dolorosa, la madera estaba estable, pero varias capas alteraban la policromía: barniz de resina vegetal, un rebarnizado de goma laca y cera superficial. La restauración consistió en retirar esas capas. La documentación incluye el conjunto terminado, comparativas y un vídeo de limpieza.'),
('arcangel-san-miguel','El Arcángel San Miguel','Pintura · Siglo XVII',['CIocEuTjTvv'],'La claridad del color','Una película de barniz amarillento impedía apreciar los colores de una pintura cuyo soporte y estratos pictóricos se encontraban en buen estado.','Círculo de los Rizi · Óleo sobre lienzo · 200 × 130 cm','Retirada de los viejos barnices oxidados.'),
('retrato-balaca','Retrato de niño, de Balaca','Pintura · Hacia 1865',['CBOGTUyDKiR'],'Un retrato sobre caoba','Una pequeña pintura de Ricardo Balaca con un barniz grueso y amarillento, además de depósitos de suciedad superficial.','Ricardo Balaca · Óleo sobre caoba · 35 × 25 cm','Retirada del barniz envejecido y limpieza de suciedad superficial.'),
('huida-a-egipto','La Huida a Egipto','Pintura · 1862',['CAvZbNYDLKG'],'Recuperar una escena','Francisco Díaz Carreño presentó esta pintura en la Exposición Nacional de 1862, según la documentación del estudio.','Francisco Díaz Carreño · Óleo sobre lienzo · 120 × 97 cm','Limpieza de depósitos de polvo, humo y contaminación, y retirada de un barniz oxidado y amarilleado.'),
('inmaculada-concepcion','Inmaculada Concepción','Pintura · Siglo XVIII',['CEL9SM_DliU'],'Leer bajo el barniz','Una pintura anónima con depósitos de suciedad, barniz oxidado y repintes posteriores a su realización.','Anónimo · Óleo sobre lienzo · 200 × 140 cm','Limpieza de la superficie y retirada de repintes documentados en la publicación del estudio.')]
case_specs.append(('florero-baudesson','Florero, copia de Baudesson','Pintura y marco · Siglo XVIII',['B2jGiSDjazY'],'La profundidad de las flores','Un florero anónimo francés, copia de Nicolas Baudesson, llegó con el lienzo destensado, roturas y una película pictórica frágil. La suciedad y un barniz espeso y amarillento ocultaban la luz y el color. La intervención también recuperó la lectura del dorado del marco.','Anónimo francés · Copia de Nicolas Baudesson · Siglo XVIII','Consolidación de la pintura con papel japonés, cola natural, calor y presión; colocación de parches; limpieza de suciedad y barniz envejecido; estucado y reintegración de pérdidas; barnizado final. En el marco se retiró la purpurina oxidada que cubría el dorado antiguo.'))
for s,t,k,ids,h,intro,facts,process in case_specs:
 if not all(id in by for id in ids):continue
 media=[m for id in ids for m in by[id].get('media',[]) if m.get('status')=='downloaded'];cases.append(dict(slug=s,title=t,kind=k,ids=ids,heading=h,intro=intro,facts=facts,process=process,media=media))
BASE='/new-design/'
def link(path):return BASE+path
mark='<img class="brand-emblem" src="/new-design/assets/brand/demoreto-emblem.webp" width="66" height="66" alt="" aria-hidden="true">'
def page(path,title,body,active='',home=False):
 nav=''.join(f'<a {"aria-current=page" if active==key else ""} href="{link(url)}">{label}</a>' for key,url,label in [('rest','restauracion/','Restauración'),('art','obra/','Obra de Antonio'),('studio','estudio/','El estudio'),('contact','contacto/','Contacto')])
 intro_preload='<link rel="preload" as="image" href="/new-design/assets/loader/engravings.webp" fetchpriority="high">' if home else ''
 seo=metadata(path,title,body,BASE)
 doc=f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,follow">{seo}<link rel="icon" type="image/x-icon" href="{BASE}assets/brand/favicon-dm-v2.ico" sizes="16x16 32x32 48x48 64x64"><link rel="icon" type="image/png" sizes="32x32" href="{BASE}assets/brand/favicon-dm-v2-32.png"><link rel="icon" type="image/png" sizes="192x192" href="{BASE}assets/brand/favicon-dm-v2-192.png"><link rel="icon" type="image/svg+xml" sizes="any" href="{BASE}assets/brand/favicon-dm-v2.svg"><link rel="apple-touch-icon" sizes="180x180" href="{BASE}assets/brand/favicon-dm-v2-180.png">{intro_preload}<link rel="stylesheet" href="{BASE}style.css"><script defer src="{BASE}site.js"></script></head><body class="{'home' if home else ''}"><a class="skip" href="#main">Saltar al contenido</a><header><a class="brand" href="{BASE}" aria-label="DeMoreto, inicio">{mark}<span>DeMoreto<small>CONSERVACIÓN & ARTE</small></span></a><nav aria-label="Principal">{nav}</nav><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav">Menú <span>☰</span></button></header><div id="mobile-nav" hidden>{nav}</div><main id="main">{body}</main><footer><div class="footer-top"><p>La historia continúa.<br><em>Hablemos de su obra.</em></p><a class="action" href="{BASE}contacto/">{{ CONTACTAR CON EL ESTUDIO }}</a></div><div class="footer-bottom"><a class="footer-logo" href="{BASE}">DeMoreto</a><span>Antonio G. Ariza<br>Conservación, restauración y pintura · Madrid</span><a href="/new-design/archivo/">Archivo del estudio ↗</a><a href="https://www.instagram.com/moreto_restauracion/">Instagram ↗</a><a href="mailto:agariza@gmail.com">agariza@gmail.com ↗</a></div><div class="fine">© DeMoreto <span>Una mirada al arte, a través del tiempo.</span></div></footer><dialog id="lightbox"><button class="lightbox-close" aria-label="Cerrar imagen">Cerrar ×</button><img alt=""><p></p></dialog></body></html>'''
 dest=OUT/path/'index.html' if path else OUT/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(doc)
def img(src,alt,cls='',eager=False):
 attrs=''
 try:
  with Image.open(AS/src) as im:attrs=f' width="{im.width}" height="{im.height}"'
 except (OSError,FileNotFoundError):pass
 return f'<img src="{BASE}assets/{src}" alt="{esc(alt)}" class="{cls}"{attrs} loading="{"eager" if eager else "lazy"}" decoding="async">'

def artcard(a):return f'<a class="catalog-card {"panorama" if a["width"]/a["height"]>4 else ""}" href="{BASE}obra/{a["slug"]}/"><div class="art-image">{img(a["slug"]+"-700.webp",a["title"])}</div><div class="card-label"><h3>{a["title"]}</h3><span>Antonio G. Ariza <i>↗</i></span></div></a>'
def casecard(c):
 m=next((m for m in c['media'] if m['type']=='image'),None);visual=img('restoration/'+m['file'],c['title']) if m else '<span class="video-card">Un gesto.<br><em>Un proceso.</em><b>▷</b></span>'
 return f'<a class="catalog-card" data-category="{esc("Pintura" if c["kind"].startswith("Pintura") else c["kind"].split(" ·")[0])}" href="{BASE}restauracion/{c["slug"]}/"><div class="case-image">{visual}</div><div class="card-label"><small>{c["kind"]}</small><h3>{c["title"]}</h3><span>Ver documentación <i>↗</i></span></div></a>'
def sectionhead(n,title,url,label):return f'<div class="section-head"><span class="eyebrow">{n}</span><h2>{title}</h2><a class="action" href="{BASE}{url}">{{ {label} }}</a></div>'
home=f'''<section class="hero"><div class="hero-copy"><span class="eyebrow">EL ESTUDIO · MADRID</span><h1>El arte de<br><em>conservar.</em></h1><p>Conservación y restauración de obras de arte.<br>Una mirada atenta a la materia y a su historia.</p><a class="action" href="{BASE}restauracion/">{{ EXPLORAR RESTAURACIONES }}</a><div class="hero-foot"><span>Antonio G. Ariza</span><span>↓</span></div></div><a class="hero-art" href="{BASE}restauracion/san-juan-evangelista/">{img('restoration/CbFjWUWKX_S-03.jpg','Guirnalda con San Juan Evangelista, obra restaurada',eager=True)}<span>Guirnalda con San Juan Evangelista · Siglo XVII <i>↗</i></span></a></section>
<section class="collection">{sectionhead('I / CONSERVACIÓN','Obras que vuelven a contar.','restauracion/','VER RESTAURACIONES')}<div class="catalog-grid">{''.join(casecard(next(c for c in cases if c['slug']==slug)) for slug in ['florero-baudesson','virgen-de-tomalos','calvario-anchieta'])}</div></section>
<section class="studio-spread home-studio"><div class="studio-copy"><span class="eyebrow">UNA VIDA ENTRE OBRAS</span><h2>La mirada de<br><em>Antonio.</em></h2><p>Restaurador, historiador del arte y pintor. Tres formas de acercarse a una misma materia.</p><p>La práctica del taller convive con la investigación de la pintura española del siglo XIX y con una obra pictórica propia.</p><a class="action" href="{BASE}estudio/">{{ CONOCER A ANTONIO }}</a></div><figure class="studio-portrait">{img('antonio-restaurando-mejorada.webp','Antonio G. Ariza restaurando una pintura de gran formato en el taller')}</figure></section>
<section class="collection">{sectionhead('II / PINTURA','La obra de Antonio.','obra/','EXPLORAR LAS 16 OBRAS')}<div class="catalog-grid">{''.join(artcard(next(a for a in art if a['slug']==s)) for s in ['tanguy-1','chapel','sunset-3'])}</div></section><section class="manifesto"><span class="eyebrow">MATERIA · MEMORIA · MIRADA</span><p>Conservar la materia.</p><p><em>Comprender su historia.</em></p><a class="action" href="{BASE}estudio/">{{ EL TALLER Y SU PRÁCTICA }}</a></section>'''
page('', 'Conservación y arte',home,home=True)
page('obra','Obra de Antonio',f'<section class="page-title"><span class="eyebrow">II / EL ARTISTA</span><h1>Obra de <em>Antonio.</em></h1><p>Una colección de dieciséis pinturas.<br>Color, atmósfera y huellas de la materia.</p></section><div class="catalog-toolbar"><span>16 obras · Antonio G. Ariza</span><span>Catálogo de pintura</span></div><div class="catalog-grid art-catalog">'+''.join(artcard(a) for a in art)+'</div>','art')
for i,a in enumerate(art):
 s=a['slug'];body=f'<div class="breadcrumb"><a href="{BASE}obra/">Obra de Antonio</a> / {a["title"]}</div><section class="object-layout"><aside><span class="eyebrow">OBRA ORIGINAL / {i+1:02}</span><h1>{a["title"]}</h1><p class="artist">Antonio G. Ariza</p><dl><div><dt>Colección</dt><dd>Pintura</dd></div><div><dt>Vistas</dt><dd>Obra, detalle y ambiente</dd></div></dl><a class="action" href="{BASE}contacto/?obra={esc(a["title"])}">{{ CONSULTAR SOBRE ESTA OBRA }}</a><p class="aside-note">Para conocer la ficha técnica y más información sobre esta pieza, contacte con el estudio.</p></aside><div class="object-images"><figure><button class="zoom" data-full="{BASE}assets/{s}-2600.webp" data-caption="{esc(a["title"])} — obra completa">{img(s+"-1800.webp",a["title"],eager=True)}<span>Ampliar ↗</span></button><figcaption>01 / Obra completa</figcaption></figure><figure class="detail-figure"><button class="zoom" data-full="{BASE}assets/{s}-detail.webp" data-caption="{esc(a["title"])} — detalle">{img(s+"-detail.webp","Detalle de "+a["title"])}<span>Ampliar ↗</span></button><figcaption>02 / Detalle de la superficie</figcaption></figure><figure class="context-figure"><button class="zoom" data-full="{BASE}assets/contexts/{s}.webp" data-caption="{esc(a["title"])} — la obra en el espacio">{img("contexts/"+s+".webp",a["title"]+" en el espacio")}<span>Ampliar ↗</span></button><figcaption>03 / La obra en el espacio</figcaption></figure></div></section><div class="next-work"><span>CONTINUAR LA COLECCIÓN</span><a href="{BASE}obra/{art[(i+1)%len(art)]["slug"]}/">{art[(i+1)%len(art)]["title"]} →</a></div>'
 page('obra/'+s,a['title'],body,'art')
filters='<div class="filters" role="group" aria-label="Filtrar restauraciones">'+''.join(f'<button data-filter="{v}" aria-pressed="{str(v=="Todas").lower()}">{v}</button>' for v in ['Todas','Pintura','Escultura','Fotografía coloreada','Proceso','Cuaderno'])+'</div>'
page('restauracion','Restauración',f'<section class="page-title"><span class="eyebrow">I / EL RESTAURADOR</span><h1>La memoria<br><em>de las obras.</em></h1><p>Pintura, escultura y otras formas de patrimonio.<br>Una selección documentada de intervenciones del estudio.</p></section>{filters}<div class="catalog-grid restoration-catalog">'+''.join(casecard(c) for c in cases)+'</div><div class="archive-link"><h2>Del taller, página a página.</h2><a class="action" href="/new-design/archivo/">{{ EXPLORAR EL ARCHIVO COMPLETO RECUPERADO }}</a></div><p class="archive-note">Documentación procedente del archivo público del estudio. Las fechas de publicación no equivalen necesariamente a las fechas de intervención.</p>','rest')
for i,c in enumerate(cases):
 gallery=''
 captions={
 'florero-baudesson':['El florero y su marco tras la intervención','Estado anterior a la intervención','Tulipán antes de la limpieza','Tulipán después de la limpieza','Detalle floral antes de la limpieza','Detalle floral después de la limpieza','Marco: comparación de la purpurina con el dorado antiguo'],
 'virgen-de-tomalos':['Comparación del estado de la pintura','Detalle de una rotura y su tratamiento','Suciedad y alteraciones de la superficie','Reverso del lienzo: reparaciones antiguas','Presentación de la obra enmarcada','Detalle de la composición','Detalle de la policromía y ornamentación'],
 'calvario-anchieta':['El conjunto del Calvario restaurado','Estado anterior del conjunto','Limpieza de la Dolorosa: vídeo del proceso','Dolorosa: comparación de estados','Detalle de la Dolorosa tras la limpieza']}
 for n,m in enumerate(c['media']):
  src='restoration/'+m['file'];label=f'{n+1:02} / '+(captions[c['slug']][n] if c['slug'] in captions else 'Documentación del estudio')
  visual=f'<video controls preload="metadata" playsinline poster="{BASE}assets/{src}.poster.jpg" src="{BASE}assets/{src}"></video>' if m['type']=='video' else f'<button class="zoom" data-full="{BASE}assets/{src}" data-caption="{esc(c["title"])} · Documento {n+1}">{img(src,c["title"]+" — documento "+str(n+1),eager=n==0)}<span>Ampliar ↗</span></button>'
  gallery+=f'<figure>{visual}<figcaption>{label}</figcaption></figure>'
 sources=''
 for id in c['ids']:
  p=by[id];date=datetime.datetime.fromtimestamp(p.get('timestamp',0),datetime.timezone.utc).strftime('%d.%m.%Y');sources+=f'<details class="source"><summary>Nota original del estudio · {date}</summary><div class="source-text">{esc(p.get("caption",""))}</div><a href="{p["url"]}">Ver publicación original ↗</a></details>'
 body=f'<div class="breadcrumb"><a href="{BASE}restauracion/">Restauración</a> / {c["title"]}</div><section class="object-layout restoration-detail"><aside><span class="eyebrow">{c["kind"]}</span><h1>{c["title"]}</h1><p>{c["facts"]}</p><p class="aside-note">Conservación y restauración<br>Estudio DeMoreto</p><a class="action" href="{BASE}contacto/?tema=restauracion">{{ CONSULTAR UNA RESTAURACIÓN }}</a></aside><div class="object-images"><div class="case-intro"><h2>{c["heading"]}</h2><p>{c["intro"]}</p><h3>La intervención</h3><p>{c["process"]}</p></div>{gallery}<div class="source-block"><h2>Del archivo del estudio</h2>{sources}</div></div></section><div class="next-work"><span>SIGUIENTE HISTORIA</span><a href="{BASE}restauracion/{cases[(i+1)%len(cases)]["slug"]}/">{cases[(i+1)%len(cases)]["title"]} →</a></div>'
 page('restauracion/'+c['slug'],c['title'],body,'rest')
studio=f'<section class="page-title"><span class="eyebrow">III / EL ESTUDIO</span><h1>Antonio G. Ariza.<br><em>Una mirada, tres prácticas.</em></h1></section><section class="studio-spread biography"><div class="studio-copy"><span class="eyebrow">RESTAURACIÓN · INVESTIGACIÓN · PINTURA</span><h2>El conocimiento<br>y las manos.</h2><p>Antonio G. Ariza es licenciado en Historia del Arte por la Universidad Complutense de Madrid y restaurador formado en la Escuela Superior de Conservación y Restauración de la Comunidad de Madrid.</p><p>Compagina la restauración con la investigación, con especial atención a la pintura española del siglo XIX. Su práctica como pintor abre otra relación con el color y con la superficie.</p><a class="action" href="{BASE}obra/">{{ CONOCER SU OBRA }}</a></div>{img("studio-3.webp","Trabajo de restauración en el estudio",eager=True)}</section><section class="wide-photo">{img("studio-2.webp","Vista del taller DeMoreto")}<p>El taller · Archivo del estudio</p></section><section class="practice"><span class="eyebrow">EL TRABAJO DEL ESTUDIO</span><div><h2>Cada obra requiere<br><em>su propia atención.</em></h2><p>La documentación de las intervenciones permite conocer el estado de las piezas, los materiales afectados y las decisiones del proceso.</p><div class="practice-row"><span>01</span><h3>Pintura</h3><p>Conservación de soportes y estratos pictóricos, limpieza y reintegración.</p></div><div class="practice-row"><span>02</span><h3>Escultura</h3><p>Consolidación de madera, conservación de policromías y tratamiento de pérdidas.</p></div><div class="practice-row"><span>03</span><h3>Investigación</h3><p>Historia del arte y estudio de la pintura española del siglo XIX.</p></div></div></section>'
page('estudio','El estudio',studio,'studio')
contact=f'<section class="page-title"><span class="eyebrow">IV / CONTACTO</span><h1>Todo empieza<br><em>con una conversación.</em></h1></section><section class="contact-layout contact-direct"><div><span class="eyebrow">ESCRIBA AL ESTUDIO</span><h2>Hablemos de su obra.</h2><p>Para consultar una restauración o conocer la obra de Antonio, escríbanos directamente.</p><a class="contact-email" id="contact-email" href="mailto:agariza@gmail.com">agariza@gmail.com ↗</a><div class="contact-actions"><a class="action" id="email-action" href="mailto:agariza@gmail.com">{{ ESCRIBIR UN CORREO ↗ }}</a><button class="action" type="button" id="copy-email">{{ COPIAR DIRECCIÓN }}</button></div><p class="copy-status" id="copy-status" role="status"></p><p class="contact-help">Puede utilizar su aplicación de correo o copiar la dirección en su correo web.</p><p class="enquiry-context" id="enquiry-context" hidden></p><dl><div><dt>Estudio</dt><dd>Madrid · Visitas con cita previa</dd></div><div><dt>Archivo y actualidad</dt><dd><a href="https://www.instagram.com/moreto_restauracion/">@moreto_restauracion ↗</a></dd></div></dl></div><aside class="contact-guidance"><span class="eyebrow">PARA EMPEZAR</span><h2>Una primera<br><em>mirada.</em></h2><p>Si desea restaurar una pieza, adjunte a su correo una fotografía general y detalles de las zonas que le preocupan.</p><p>Las medidas aproximadas, el material y cualquier información sobre su historia nos ayudarán a conocerla mejor.</p><p>Para consultar sobre una pintura de Antonio, indique el título de la obra.</p></aside></section>'

page('contacto','Contacto',contact,'contact')
archive_cards=[]
for i,p in enumerate(posts):
 if p.get('status')!='public-data-found':continue
 code=p['code'];date=datetime.datetime.fromtimestamp(p.get('timestamp',0),datetime.timezone.utc).strftime('%d.%m.%Y')
 caption=p.get('caption') or ''; first=next((x.strip() for x in caption.splitlines() if len(x.strip())>5),'Documento del estudio')
 title=first[:110]+('…' if len(first)>110 else '')
 matching=next((c for c in cases if code in c['ids']),None)
 visual=next((m for m in p.get('media',[]) if m.get('file') and m['type']=='image'),None)
 video=next((m for m in p.get('media',[]) if m.get('file') and m['type']=='video'),None)
 cover=img('restoration/'+visual['file'],title) if visual else img('restoration/'+video['file']+'.poster.jpg',title) if video else '<span class="video-card">Del taller.<br><em>En movimiento.</em><b>▷</b></span>'
 archive_cards.append(f'<a class="catalog-card archive-card" data-search="{esc(caption.lower())}" href="{BASE}archivo/{code}/"><div class="case-image">{cover}</div><div class="card-label"><small>{date}</small><h3>{esc(title)}</h3><span>Leer publicación <i>↗</i></span></div></a>')
 gallery=''
 for n,m in enumerate(p.get('media',[])):
  if not m.get('file'):continue
  src='restoration/'+m['file']
  visual=f'<video controls preload="metadata" playsinline poster="{BASE}assets/{src}.poster.jpg" src="{BASE}assets/{src}"></video>' if m['type']=='video' else f'<button class="zoom" data-full="{BASE}assets/{src}" data-caption="Documento {n+1} · {date}">{img(src,"Documento "+str(n+1)+" del estudio")}<span>Ampliar ↗</span></button>'
  gallery+=f'<figure>{visual}<figcaption>{n+1:02} / Archivo de la publicación · {date}</figcaption></figure>'
 more=f'<a class="action" href="{BASE}restauracion/{matching["slug"]}/">{{ VER EL PROYECTO }}</a>' if matching else ''
 body=f'<div class="breadcrumb"><a href="{BASE}archivo/">Archivo del estudio</a> / {date}</div><section class="object-layout archive-detail"><aside><span class="eyebrow">CUADERNO DEL ESTUDIO</span><h1>{esc(title)}</h1><p>Publicado el {date}</p>{more}<p class="aside-note">Texto y documentación originales de la publicación. Las imágenes pueden incluir referencias históricas además de las obras intervenidas.</p><a class="action" href="{p["url"]}">{{ VER EN INSTAGRAM ↗ }}</a></aside><div class="object-images"><div class="case-intro"><h2>Notas del taller</h2><div class="source-text">{esc(caption) if caption else "Esta publicación no incluye texto del estudio."}</div></div>{gallery}</div></section>'
 page('archivo/'+code,title,body,'rest')
page('archivo','Archivo del estudio',f'<section class="page-title"><span class="eyebrow">DOCUMENTOS / CUADERNO</span><h1>El archivo<br><em>del estudio.</em></h1><p>Restauraciones, procesos y notas de historia del arte. Las publicaciones del estudio, con sus textos y secuencias de imágenes.</p></section><div class="archive-search"><label for="archive-search">Buscar en el archivo</label><input type="search" id="archive-search" placeholder="Una obra, un artista, un material…"><span id="archive-count" role="status">{len(archive_cards)} publicaciones</span></div><div class="catalog-grid">'+''.join(archive_cards)+'</div>','rest')
(OUT/'content.json').write_text(json.dumps({'artworks':art,'projects':[{k:v for k,v in c.items() if k!='media'} for c in cases]},ensure_ascii=False,indent=2))
print('Built',len(list(OUT.rglob('index.html'))),'pages;',len(art),'artworks;',len(cases),'restoration/archive stories')
